### ISSUE TITLE
Trade executed at exchange and not seen on simulation charts

### ISSUE THREAD

**Issue by EduRemix** [Superalgos/Releases#1]
As you can see, Take Position was ejecuted in Poloniex at 02:15:11

![Screenshot 2019-08-17 at 09 39 35](https://user-images.githubusercontent.com/54202149/63208483-e7703100-c0d4-11e9-8f99-15ba2bd23c99.png)

Here you can see the candle at 02:15:11
In the simulator the conditions for Take Position was almost accomplished, anyway in Poloniex the order was placed. 

![Screenshot 2019-08-17 at 10 02 17](https://user-images.githubusercontent.com/54202149/63208578-1fc43f00-c0d6-11e9-8183-072da9d5896a.png)

Later, Take Position was ejecuted in simulator at 05:53 aprox, but this has not happened in Poloniex.

![Screenshot 2019-08-17 at 09 41 54](https://user-images.githubusercontent.com/54202149/63208485-01117880-c0d5-11e9-9e6d-cab6e3b5a9db.png)

**Comment by Luis-Fernando-Molina** [comment]
Thanks for reporting it. This is related to an issue I am currently working on. It is related to the fact that I enabled the last candle not to be really closed. I will rollback that change so that does not happen again.

NOTE: Avoid until version 2 using the ticker object in conditions code because that will trigger this same behavior. You can use the ticker object only in formulas for the time being.

**Comment by Luis-Fernando-Molina** [comment]
Fixed. A limitation on the current version prevents to use the ticker at conditions, if you do, you might enter into this problem. Use it only in formulas.
