### ISSUE TITLE
Separate buttons for running indicators, simulations and live trading

### ISSUE THREAD

**Issue by julian-molina** [Superalgos/Releases#9]
The app would offer a lot more flexibility to users if we had three separate, independent buttons for running indicators, simulations and live trading.

Advantages:

* Users may want to fine tune a strategy even after starting trading live.

* Users may want to run indicators only as they start the app, before actually running a simulation. The strategy may not be complete and simulation ready, but indicators could be running any way.

* Separate buttons would eliminate the need to detach the API key element to switch back and forth between different functions.

**Comment by Luis-Fernando-Molina** [comment]
This criteria is not aligned on how the UI is going to evolve, which is certainly not going to evolve in having a lot of buttons. 

Later I will introduce icons for the processes that builds the data-sets and you will have more fine control on what run, when and how. In the meantime I wont implement you will have to live with this way since I am not up to doing provisional work that will be discarded later. 

The overall criteria which is true not only for the type of execution but also for almost every other details is that:

> **Whatever is attached directly or indirectly to the Definition object at the designer, influences the way it runs**
